---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo-bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo-bar
  template:
    metadata:
      labels:
        app: http-echo-bar
        metadata: http-echo
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        args:
        - "-text=bar"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo-bar
spec:
  selector:
    app: http-echo-bar
  ports:
  - port: 5678
    targetPort: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-echo-bar-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /bar(/|$)(.*)
        backend:
          service:
            name: http-echo-bar
            port:
              number: 5678
