apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo-foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo-foo
  template:
    metadata:
      labels:
        app: http-echo-foo
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        args:
        - "-text=foo"
        ports:
        - containerPort: 5678
